version: 2

sources:
  - name: crmuser
    description: "customer related information"
    schema: public
    tables:
      - name: branches
        description: "It contain branches information"
      - name: products
        description: "It contain products information"  
      - name: customers
        description: "It contain customers information"
      - name: accounts
        description: "It contain accounts information"
