version: 2

sources:
  - name: crmuser
    description: "customer related information"
    schema: bronze
    tables:
      - name: branch
        description: "branch master information"
      - name: customer
        description: "it contain customer information"
      - name: account
        description: "It contain account realted information"
      - name: transactions
        description: "account transaction ledger information"
      - name: lien
        description: "lien holds/encumbrances placed on accounts"
      - name: ratelist
        description: "daily foreign exchange rate list"
