dbt_first_class:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: ""
      port: 5432
      schema: public
      threads: 2
      type: postgres
      user: newanatandukar
  target: dev
